import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import bearPlexLogo from "../images/logo.PNG";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Home1 from "../components/home1";
import Home3 from "../components/home3";
import Home4 from "../components/home4";
import Home5 from "../components/home5";
import Home6 from "../components/home6";
import Navbar from "@/components/navbar";
import Home7 from "@/components/home7";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [modal, setModal] = useState(false);

  function handlebtnfalse() {
    console.log("False Called");
    setModal(false);
  }
  function handlebtntrue() {
    console.log("true Called");
    setModal(true);
  }
  useEffect(() => {}, [modal]);
  console.log(modal);
  return (
    <>
      {/* #region head */}
      <Head>
        <title>BearPlex Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* #end region head */}

      {/* #region Mobile Nabar */}

      {/* #end region mobile Navbar */}
      {/* #region Web Nav and first Componenet */}
      <div className="h-[140vh] bg-[url('https://bearplex.com/wp-content/uploads/2022/04/cover-bg.jpg')] pt-[1px] md:h-[100vh] ">
        <Navbar />
        {/* #end region of Web Navbar */}
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <Home1 />
      </div>
      <br />
      <br />
      <br />
      <br />
      <div className="mx-auto w-screen flex justify-center">
        <h1 className="w-3/5 text-2xl">
          Our mission is to provide our clients with Top 3% globally distributed
          business, design & technology talent, ready to tackle your most
          important initiatives. Build our remote tech team with us in the next
          48 hours with zero risk guaranteed.
        </h1>
      </div>
      <br />
      <br />
      <br />

      <Home3 />
      <br />
      <br />
      <br />
      <br />
      <br />
      <Home4 />
      <br />
      <br />
      <br />
      <Home5 />
      <br />
      <br />
      <br />
      <br />
      <br />
      <br />
      <Home6 />
      <br />
      <br />
      <br />
      <Home7 />
    </>
  );
}
